with_default_config = true

[keymaps]
up = "k"
down = "j"
left = "h"
right = "l"
exit = "ctrl+c"
open = "o"
search = "/"
interact = "i"
send = "ctrl+enter"

[keymaps.focus]
up = "shift+K"
down = "shift+J"
left = "shift+H"
right = "shift+L"

[slack]
client_id = ""
client_secret = ""

[status_line.left]
template = " %mode% <> %channel% "
separator = "\ue0b4"

[status_line.right]
template = " %team% <> %user% "
separator = "\ue0b6"
